# Generated by Django 3.0.6 on 2021-01-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20210117_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='numrs_star',
            field=models.IntegerField(choices=[(1, 'worst'), (2, 'bad'), (3, 'not bad'), (4, 'good'), (5, 'Excellent')]),
        ),
        migrations.AlterField(
            model_name='album',
            name='relase_date',
            field=models.DateField(),
        ),
    ]
