# Generated by Django 3.0.6 on 2021-02-07 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20210117_1729'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='album',
            table='Album',
        ),
        migrations.AlterModelTable(
            name='musician',
            table='Musician',
        ),
    ]
